name: luogo
description: "Secure and simple location sharing app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  s5_messenger:
    path: ../s5_messenger/
  cupertino_icons: ^1.0.8
  lib5: ^0.2.0
  hive: ^2.2.3
  s5: ^0.2.0
  logger: ^2.5.0
  adaptive_dialog: ^2.4.1
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter_map_pmtiles: ^1.0.5
  maplibre_gl: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pmtiles_style.json
