name: luogo
description: "Secure and simple location sharing app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.4+7

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  s5_messenger:
    # path: ../s5-things/s5_messenger/
    git: https://github.com/s5-dev/s5_messenger.git
  s5:
    # path: ../s5-things/s5-dart/
    git: 
      url: https://github.com/lukehmcc/s5-dart.git
      ref: 0.2.0-patched
  lib5: 
    # path: ../s5-things/lib5/
    git: 
      url: https://github.com/lukehmcc/lib5.git
      ref: 0.2.0-patched
  cupertino_icons: ^1.0.8
  hive_ce: ^2.11.2
  logger: ^2.5.0
  adaptive_dialog: ^2.4.1
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter_map_pmtiles: ^1.0.5
  maplibre_gl: ^0.22.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  path: ^1.9.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.1
  flutter_colorpicker: ^1.1.0
  image: ^4.3.0
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  msgpack_dart: ^1.0.1
  uuid: ^4.5.1
  intl: ^0.20.2
  background_fetch: ^1.4.0
  get_it: ^8.1.0
  flutter_svg: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.5.1
  hive_ce_generator: 1.9.2
  flutter_launcher_icons: "^0.14.4"
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/pmtiles_style.json
    - assets/pin.png
    - assets/fake-map.png
