import 'package:flutter/material.dart';
import 'dart:math';

class SillyCircularProgressIndicator extends StatelessWidget {
  const SillyCircularProgressIndicator({super.key});

  @override
  Widget build(BuildContext context) {
    final randomIndex = Random().nextInt(100);
    final message = _loadingMessages[randomIndex];

    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const CircularProgressIndicator(),
            const SizedBox(height: 20),
            Text(
              message,
              style: Theme.of(context).textTheme.titleMedium,
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }

  static const List<String> _loadingMessages = [
    "Getting up to temperature",
    "Gimme a sec",
    "Warming up the hamster wheel",
    "Counting backwards from infinity",
    "Baking digital cookies",
    "Herding cats",
    "Convincing electrons to cooperate",
    "Asking the AI overlords for permission",
    "Polishing the pixels",
    "Reheating leftover bits",
    "Teaching ants to type",
    "Defragging the fun drive",
    "Aligning the cosmic ducks",
    "Charging the flux capacitor",
    "Consulting the oracle",
    "Bending spacetime",
    "Downloading more RAM",
    "Calibrating the funny bone",
    "Searching for lost socks",
    "Reversing the polarity",
    "Petting the server hamsters",
    "Sharpening the pixels",
    "Dusting off the algorithms",
    "Convincing the 1s and 0s to dance",
    "Inflating the internet balloons",
    "Uncrumpling the paperclips",
    "Reassembling the puzzle pieces",
    "Tickling the processors",
    "Charging the joke batteries",
    "Finding the missing semicolon",
    "Wrestling with the gremlins",
    "Brewing fresh coffee for the CPU",
    "Training the neural network to juggle",
    "Waiting for the paint to dry",
    "Teaching old code new tricks",
    "Folding the digital laundry",
    "Counting to 10 in binary",
    "Untangling the spaghetti code",
    "Convincing the cloud to rain data",
    "Polishing the crystal ball",
    "Waiting for the stars to align",
    "Charging the quantum batteries",
    "Debugging reality",
    "Finding the any key",
    "Rehearsing the digital symphony",
    "Waiting for the turtles to stack",
    "Teaching the AI to appreciate puns",
    "Defrosting the cache",
    "Recharging the funny capacitors",
    "Waiting for the second shoe to drop",
    "Counting the grains of digital sand",
    "Waiting for the paint to compile",
    "Teaching the app to walk",
    "Waiting for the internet to refill",
    "Convincing the bits to behave",
    "Waiting for the magic to happen",
    "Bribing the progress bar",
    "Waiting for the electrons to finish their coffee",
    "Teaching the cloud to rain data",
    "Waiting for the bits to settle",
    "Convincing the pixels to stay in line",
    "Waiting for the hamsters to wake up",
    "Teaching the app to tie its shoes",
    "Waiting for the internet to warm up",
    "Convincing the code to compile",
    "Waiting for the database to finish its yoga",
    "Teaching the server to meditate",
    "Waiting for the bits to dry",
    "Convincing the Wi-Fi to cooperate",
    "Waiting for the cache to bake",
    "Teaching the app to whistle",
    "Waiting for the quantum foam to settle",
    "Convincing the firewall to let us through",
    "Waiting for the bits to ferment",
    "Teaching the algorithm to tell jokes",
    "Waiting for the cloud to stop raining",
    "Convincing the cookies to bake",
    "Waiting for the database to stretch",
    "Teaching the app to snap its fingers",
    "Waiting for the internet to take a deep breath",
    "Convincing the framework to behave",
    "Waiting for the pixels to dry",
    "Teaching the API to sing",
    "Waiting for the cache to cool",
    "Convincing the compiler to stop complaining",
    "Waiting for the bits to percolate",
    "Teaching the app to wink",
    "Waiting for the database to finish its crossword",
    "Convincing the network to share",
    "Waiting for the electrons to line dance",
    "Teaching the UI to juggle",
    "Waiting for the cloud to stop being so fluffy",
    "Convincing the code to stop being so dramatic",
    "Waiting for the bits to finish their tea",
    "Teaching the app to do a backflip",
    "Waiting for the database to finish its nap",
    "Convincing the framework to stop being so opinionated",
    "Waiting for the pixels to finish their yoga",
    "Teaching the API to tap dance",
    "Waiting for the cache to finish its novel",
    "Convincing the compiler to be more optimistic",
    "Waiting for the bits to stop procrastinating",
  ];
}
